### PR TITLE
Load time optimisations

### PR DESCRIPTION
**Pull request by townxelliot**
This branch makes some improvements to the application's load time (details in the commits).

The improvements to the load time (measured on a Tizen device, running the app in the web runtime) are as follows:
- Load time (from white screen to app visible) is 41% of original load time (measured using video)
- Load time (from fetch start to all JS execution finished, resources loaded etc.) is 44% of original load time (measured using performance.timing)
- Page show time (from fetch start to DOMContentLoaded end)  is 48% of original page show time (measured using performance.timing)

I also added a grunt build target to produce a set of files suitable for use with the SDK.

### CODE REVIEW

**Comment by cwong1** [comment]
This merge request has been rejected for the following reasons:

1) the license.js expect README.txt, not README.md.
2) README.md contains some html formatting tags and they won't get translated by license.js when it displays the contents in the info window.

Please fixed the issues and re-submit your merge request.

**Comment by townxelliot** [comment]
Thanks for the feedback.

Please see additional commits which fix the issue you identified.

**Comment by cwong1** [comment]
After I did the merge and ran the grunt command, I then try to run build/app/index.html under chromium-browser and I still couldn't see the README.txt showing up in the license window.  I notice that the README.txt is missing from the build/app directory after I ran the grunt command.  Did I do something wrong or is there a bug in the package code?

**Pull request merged**
